### PR TITLE
Update

### PR DESCRIPTION
**Pull request by jburel**
* Add badges to readme
* Fix hyperlink
* Add flake8 check and fix error
* Bump action version to avoid warnings

### CODE REVIEW

**Comment by Tom-TBT** [comment]
Thank you very much for the changes JM. I will transpose them to omero-tagsearch if you don't mind.

**Comment by jburel** [comment]
I was waiting for your work on tagsearch to be completed since it will probably conflict when enalbing flake8
Happy to do it
either way is fine

**Review by Tom-TBT — APPROVED** [review]
Thank you again, everything looks good to me and I see no error on my test instance.
I will merge this if there's nothing else you want to add.

And thank you for offering to do the same for tagsearch, but I feel that I should be the one cleaning the repo. So I'll take care of that once the ongoing PR is merged.

**Comment by jburel** [comment]
No more changes from my side

**Pull request merged**
